kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
  name: entitlement-test
  labels:
    paas.redhat.com/appcode: ITOS-008
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: python-39:latest
      volumes:
      - name: etc-pki-entitlement
        mounts:
        - destinationPath: /etc/pki/entitlement
        source:
          type: Secret
          secret:
            secretName: etc-pki-entitlement
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'false'
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/faldanarh/adhoc.git'
      ref: rhel9-entitlements-rhsm
    contextDir: "entitlements/"
  runPolicy: Serial

