kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
  name: entitlement-test
  labels:
    paas.redhat.com/appcode: ITOS-008
spec:
  nodeSelector: null
  output: {}
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      env:
        - name: GIT_SSL_NO_VERIFY
          value: 'false'
      dockerfilePath: ./Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://gitlab.corp.redhat.com/ckhare/adhoc.git'
      ref: rhel9-entitlements-rhsm
    secrets:
      - secret:
          name: etc-pki-entitlement
        destinationDir: etc-pki-entitlement
      - secret:
          name: rhsm-conf
        destinationDir: rhsm-conf
      - secret:
          name: rhsm-ca
        destinationDir: rhsm-ca
    contextDir: "entitlements/"
  runPolicy: Serial

